mode: 'train'
checkpoint: 'saved_model/IMX686'
fast_ckpt: 'checkpoints/IMX686'
model_name: 'IMX686_NoiseFlow'
result_dir: 'images/'
num_gpu: 1
num_workers: 8
brightness_correct: True

dst: &base_dst
  root_dir: 'LRID'
  bias_dir: 'LRID/bias'
  ds_dir: 'LRID/resources'
  dataset: 'IMX686_Dataset' 
  dstname: 'indoor_x5'
  command: 'alldg'
  camera_type: 'IMX686'
  noise_code: 'p'
  patch_size: 64
  H: 3472
  W: 4624
  crop_per_image: 384
  croptype: 'non-overlapped'
  wp: 1023
  bl: 64
  ori: False
  clip: False
  gpu_preprocess: False
  ratio_list: [1,2,4,8,16]
dst_train:
  <<: *base_dst
  mode: 'train'
  dstname: ['indoor_x5', 'indoor_x3', 'outdoor_x3']
dst_eval:
  <<: *base_dst
  dataset: 'IMX686_Dataset'
  mode: 'eval'
  dstname: 'indoor_x5'
  ratio_list: [1,2,4,8,16]
dst_test:
  <<: *base_dst
  dataset: 'IMX686_Dataset'
  mode: 'test'
  dstname: 'outdoor_x3'
  ratio_list: [1,2,4]

arch:
  name: 'NoiseFlow'
  x_shape : [4, 256, 256]
  arch : 'sdn|unc|unc|unc|unc|giso|unc|unc|unc|unc'
  flow_permutation : 1
  lu_decomp : True

hyper:
  lr_scheduler: 'WarmupCosine'
  learning_rate: 2.0e-3
  batch_size: 1
  last_epoch: 0
  step_size: 10
  stop_epoch : 180
  T: 3
  coldstart: True
  num_workers: 4
  num_gpus: 1
  save_freq: 10
  plot_freq: 30