mode: 'evaltest'
checkpoint: 'saved_model/SonyA7S2'
fast_ckpt: 'checkpoints/SonyA7S2'
model_name: 'SonyA7S2_NoiseFlow'
result_dir: 'images/'
num_gpu: 1
num_workers: 6
brightness_correct: True

dst: &base_dst
  root_dir: 'SID'
  bias_dir: 'SonyA7S2/bias'
  ds_dir: 'SonyA7S2/resources-old'
  dataset: 'SID_Dataset' 
  dstname: 'SID'
  command: ''
  camera_type: 'SonyA7S2'
  noise_code: 'pgrq'
  patch_size: 64
  H: 2848
  W: 4256
  crop_per_image: 256
  croptype: 'non-overlapping'
  wp: 16383
  bl: 512
  ori: False
  clip: False
  gpu_preprocess: False
dst_train:
  <<: *base_dst
  mode: 'train'
  dataset: 'SID_Dataset' 
  dstname: 'SID'
dst_eval:
  <<: *base_dst
  mode: 'eval'
  dataset: 'ELD_Dataset' 
  dstname: 'ELD'
  iso_list: [800, 1600, 3200]
  ratio_list: [100, 200]
dst_test:
  <<: *base_dst
  mode: 'evaltest'
  dataset: 'SID_Dataset' 
  dstname: 'SID'

arch:
  name: 'NoiseFlow'
  x_shape : [4, 256, 256]
  arch : 'sdn|unc|unc|unc|unc|giso|unc|unc|unc|unc'
  flow_permutation : 1
  lu_decomp : True

hyper:
  lr_scheduler: 'WarmupCosine'
  learning_rate: 2.e-3
  batch_size: 1
  last_epoch: 0
  step_size: 10
  stop_epoch : 300
  T: 3
  num_workers: 4
  num_gpus: 1
  save_freq: 10
  plot_freq: 100
  best_psnr: 0.